[
  {
    "login": "bradlygreen",
    "id": 757236,
    "avatar_url": "https://avatars3.githubusercontent.com/u/757236?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/bradlygreen",
    "html_url": "https://github.com/bradlygreen",
    "followers_url": "https://api.github.com/users/bradlygreen/followers",
    "following_url": "https://api.github.com/users/bradlygreen/following{/other_user}",
    "gists_url": "https://api.github.com/users/bradlygreen/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/bradlygreen/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/bradlygreen/subscriptions",
    "organizations_url": "https://api.github.com/users/bradlygreen/orgs",
    "repos_url": "https://api.github.com/users/bradlygreen/repos",
    "events_url": "https://api.github.com/users/bradlygreen/events{/privacy}",
    "received_events_url": "https://api.github.com/users/bradlygreen/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "bradrich",
    "id": 3429878,
    "avatar_url": "https://avatars3.githubusercontent.com/u/3429878?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/bradrich",
    "html_url": "https://github.com/bradrich",
    "followers_url": "https://api.github.com/users/bradrich/followers",
    "following_url": "https://api.github.com/users/bradrich/following{/other_user}",
    "gists_url": "https://api.github.com/users/bradrich/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/bradrich/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/bradrich/subscriptions",
    "organizations_url": "https://api.github.com/users/bradrich/orgs",
    "repos_url": "https://api.github.com/users/bradrich/repos",
    "events_url": "https://api.github.com/users/bradrich/events{/privacy}",
    "received_events_url": "https://api.github.com/users/bradrich/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "calebegg",
    "id": 782920,
    "avatar_url": "https://avatars3.githubusercontent.com/u/782920?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/calebegg",
    "html_url": "https://github.com/calebegg",
    "followers_url": "https://api.github.com/users/calebegg/followers",
    "following_url": "https://api.github.com/users/calebegg/following{/other_user}",
    "gists_url": "https://api.github.com/users/calebegg/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/calebegg/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/calebegg/subscriptions",
    "organizations_url": "https://api.github.com/users/calebegg/orgs",
    "repos_url": "https://api.github.com/users/calebegg/repos",
    "events_url": "https://api.github.com/users/calebegg/events{/privacy}",
    "received_events_url": "https://api.github.com/users/calebegg/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "chuckjaz",
    "id": 372013,
    "avatar_url": "https://avatars1.githubusercontent.com/u/372013?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/chuckjaz",
    "html_url": "https://github.com/chuckjaz",
    "followers_url": "https://api.github.com/users/chuckjaz/followers",
    "following_url": "https://api.github.com/users/chuckjaz/following{/other_user}",
    "gists_url": "https://api.github.com/users/chuckjaz/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/chuckjaz/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/chuckjaz/subscriptions",
    "organizations_url": "https://api.github.com/users/chuckjaz/orgs",
    "repos_url": "https://api.github.com/users/chuckjaz/repos",
    "events_url": "https://api.github.com/users/chuckjaz/events{/privacy}",
    "received_events_url": "https://api.github.com/users/chuckjaz/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "cironunes",
    "id": 469908,
    "avatar_url": "https://avatars2.githubusercontent.com/u/469908?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/cironunes",
    "html_url": "https://github.com/cironunes",
    "followers_url": "https://api.github.com/users/cironunes/followers",
    "following_url": "https://api.github.com/users/cironunes/following{/other_user}",
    "gists_url": "https://api.github.com/users/cironunes/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/cironunes/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/cironunes/subscriptions",
    "organizations_url": "https://api.github.com/users/cironunes/orgs",
    "repos_url": "https://api.github.com/users/cironunes/repos",
    "events_url": "https://api.github.com/users/cironunes/events{/privacy}",
    "received_events_url": "https://api.github.com/users/cironunes/received_events",
    "type": "User",
    "site_admin": false
  }
]
